# Generated by Django 2.2.2 on 2020-02-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200208_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase_primera', models.CharField(max_length=100)),
                ('frase_segunda', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Titulo',
            },
        ),
    ]
