# Generated by Django 2.2.2 on 2020-02-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titulo',
            new_name='Title',
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name_plural': 'Title'},
        ),
        migrations.RenameField(
            model_name='title',
            old_name='frase_primera',
            new_name='First',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='frase_segunda',
            new_name='Second',
        ),
    ]
