# Generated by Django 2.2.2 on 2020-02-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200208_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='First',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='Second',
            new_name='second',
        ),
    ]
